#!/bin/bash

./gradlew installDebug && adb shell am start -n com.plan.yelinaung.popularmovies/com.plan.yelinaung.popularmovies.MainActivity -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
